name: Deploy CI/CD

on:
  push:
    branches: ["deploy"]
  pull_request:
    branches: ["deploy"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 서버 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PEM_SECRET }}
          scripts: |
            set -e
            cd /home/ubuntu/nolreo_wassup/nolreo_wassup_FE
            git pull origin deploy
            sudo systemctl restart nginx
